<h1>Module: <?= $this->getModuleName(); ?></h1>
<h3>Action: front/index</h3>
<ul>
    <li>
        <a href="<?php echo $this->getUrl('magecom_learning/index/index') ?>">Link to index/index</a>
    </li>
    <li>
        <a href="<?php echo $this->getUrl('magecom_learning/index/base') ?>">Link to index/base</a>
    </li>
    <li>
        <a href="<?php echo $this->getUrl('magecom_learning/front/base') ?>">Link to front/base</a>
    </li>
</ul>